- name: Update the apt-get cache
  apt: 
    update_cache: yes

- name: Install PHP
  apt:
    name: php

- name: Install Apache
  apt:
    name: apache2

- name: Copy the code from the repo
  git: repo=https://github.com/.git dest=/var/www/html/app

- name: Start Apache
  service: name=Apache2 state=started enabled=yes
